version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: e-commerce-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: letter33!
      MYSQL_DATABASE: commerce
      MYSQL_USER: letter33
      MYSQL_PASSWORD: letter33!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: